- adbDir: F:\Program Files\MuMuPlayer\nx_device\12.0\shell\adb.exe
- connectionPort: 127.0.0.1:5555
- missionList:
  - 经验值
  - 武器经验
  - 武器
  - 碎片
  - 角色突破
  - 活动
  - 塔罗
  - 星辰
- characterList:
  - 贝拉
  - 古兹曼
  - 萨曼莎
  - 泽维尔
  - 法卡尔
  - 麦莎
  - 科尔
  - 迪塔利奥
  - 拉维耶
  - 莉莉薇儿
  - 歌洛莉亚
  - 泰登
  - 诺诺薇儿
  - 列奥尼德
  - 伊奇
  - 伊南娜
  - 嘉西娅
  - 马格努斯
  - 倒吊人 "烛火"
  - 佣兵 "炎之魔女"
  - 舞娘 "蝴蝶"
  - 佣兵 "风暴神斧"
  - 药剂师 "志愿者"
  - 光辉卫士 "魔禁"
  - 弩骑士 "摧城"
  - 审判者 "鞭笞"
  - 枪骑士 "怒风"
  - 光辉侍女 "天使"
  - 黎明侍女 "黯心"
  - 倒吊人 "兵蜂"
  - 巨斧骑士 "神威"
  - 光术骑士 "耀光"
  - 山地射手 "锐眼"
  - 倒吊人 "执剑者"
  - 王国之刃 "红隼"
  - 倒吊人 "暗夜"
  - 光辉弩手 "神恩"
  - 光辉使者 "利刃"
  - 突击骑士 "神闪"
  - 薇尔德斥候
  - 王国军弓箭手
  - 黑暗之光火术士
  - 王国军火术士
  - 法皇国投枪兵
  - 法皇国冰术师
  - 骑士同盟长枪兵
  - 王国军剑盾兵
  - 王国军长枪兵
  - 骑士同盟剑盾兵
  - 黑暗之光冰术士
  - 王国军光术士
  - 法皇国剑盾兵
  - 无法者巨斧兵
  - 佣兵剑盾兵
  - 佣兵弓手
  - 佣兵长枪兵
  - 佣兵刺客
  - 无法者斧盾兵
  - 无法者长枪兵
  - 无法者刺客
  - 无法者弓兵
  - 无法者弩兵
- missionInfo:
  - id: EXP
    name: 经验值
    middleLevel: []
    difficultyCount:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    difficultyAutoCharCount:
    - 1
    - 1
    - 1
    - 2
    - 2
    - 2
    - 2
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
  - id: WUP
    name: 武器经验
    middleLevel: []
    difficultyCount:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    difficultyAutoCharCount:
    - 1
    - 1
    - 1
    - 2
    - 2
    - 2
    - 2
    - 3
    - 3
    - 3
    - 3
  - id: WEA
    name: 武器
    middleLevel:
    - A
    - B
    - C
    difficultyCount:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    difficultyAutoCharCount:
    - 1
    - 1
    - 1
    - 2
    - 2
    - 2
    - 2
    - 3
    - 3
    - 3
    - 3
  - id: SRD
    name: 碎片
    middleLevel: []
    difficultyCount:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    difficultyAutoCharCount:
    - -1
  - id: ENC
    name: 角色突破
    middleLevel:
    - A
    - B
    - C
    - D
    - E
    difficultyCount:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    difficultyAutoCharCount:
    - 1
    - 1
    - 1
    - 2
    - 2
    - 2
    - 2
    - 3
    - 3
    - 3
    - 4
    - 4
    - 4
    - 4
  - id: EVENT
    name: 活动
    middleLevel: []
    difficultyCount:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    difficultyAutoCharCount:
    - 5
    - 5
    - 5
    - 5
    - 5
    - 5
    - 5
  - id: TRT
    name: 塔罗
    middleLevel:
    - A
    - B
    - C
    difficultyCount:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    difficultyAutoCharCount:
    - 1
    - 1
    - 1
    - 2
    - 2
    - 2
    - 2
    - 3
    - 3
  - id: STAR
    name: 星辰
    middleLevel:
    - A
    - B
    - C
    - D
    - E
    difficultyCount:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    difficultyAutoCharCount:
    - 1
    - 1
    - 1
    - 2
    - 2
    - 2
    - 2
    - 3
    - 3
    - 3
    - 3
    - 3
- controlMode: adb
  windowTitle: 铃兰之剑
  processName: SoC.exe
  baseResolution:
  - 1280
  - 720
  ocrLanguages:
  - ch_sim
  - en
  taskSelection:
    startApp: false
    farmResources: false
    receiveReward: true
    receiveRewardSubtasks:
      daily: true
      exploration: true
      friend: true
      voyage: true
